project_name: s3-cisbench

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.build={{.Version}}

brews:
  - name: s3-cisbench
    tap:
      owner: rollwagen
      name: homebrew-tap
    license: Apache-2.0

# universal_binaries:
#   - replace: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
